/**
 * 模板渲染器
 * 支持简单的变量插值模板系统
 *
 * **功能**：
 * - 注册命名模板
 * - 渲染模板并插入变量
 * - 支持嵌套属性访问（如 `user.name`）
 *
 * **模板语法**：
 * - 使用 `{{ variable }}` 进行变量插值
 * - 支持嵌套属性：`{{ user.profile.name }}`
 * - 未定义变量返回空字符串
 *
 * **示例**：
 * ```typescript
 * const renderer = createTemplateRenderer();
 * renderer.register('greeting', 'Hello, {{ name }}!');
 * const result = renderer.render('greeting', { name: 'World' });
 * // 输出: "Hello, World!"
 * ```
 */
export class TemplateRenderer {
  /** 注册的模板映射 */
  private templates: Map<string, string> = new Map();

  /**
   * 注册模板
   *
   * @param name 模板名称
   * @param template 模板内容
   *
   * **示例**：
   * ```typescript
   * renderer.register('header', '// Generated at: {{ timestamp }}');
   * ```
   */
  register(name: string, template: string): void {
    this.templates.set(name, template);
  }

  /**
   * 渲染模板
   *
   * @param name 模板名称
   * @param context 渲染上下文，包含模板变量
   * @returns 渲染后的字符串
   * @throws 如果模板不存在则抛出错误
   *
   * **示例**：
   * ```typescript
   * const result = renderer.render('header', {
   *   timestamp: new Date().toISOString()
   * });
   * ```
   */
  render(name: string, context: Record<string, unknown>): string {
    const template = this.templates.get(name);

    if (!template) {
      throw new Error(`Template not found: ${name}`);
    }

    return this.interpolate(template, context);
  }

  /**
   * 在模板中插值变量
   *
   * @param template 模板字符串
   * @param context 渲染上下文
   * @returns 插值后的字符串
   *
   * **处理逻辑**：
   * - 查找所有 `{{ variable }}` 模式
   * - 从上下文中获取变量值
   * - 支持嵌套属性访问（点号分隔）
   * - 未定义变量替换为空字符串
   *
   * @private
   */
  private interpolate(template: string, context: Record<string, unknown>): string {
    return template.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_, key) => {
      const value = this.getNestedValue(context, key);
      return value !== undefined ? String(value) : '';
    });
  }

  /**
   * 从对象中获取嵌套属性值
   *
   * @param obj 源对象
   * @param path 属性路径（点号分隔）
   * @returns 属性值，未找到则返回 undefined
   *
   * **示例**：
   * ```typescript
   * getNestedValue({ user: { name: 'John' } }, 'user.name'); // 'John'
   * getNestedValue({ user: { name: 'John' } }, 'user.age');  // undefined
   * ```
   *
   * @private
   */
  private getNestedValue(obj: Record<string, unknown>, path: string): unknown {
    const keys = path.split('.');
    let current: unknown = obj;

    for (const key of keys) {
      if (current === null || current === undefined) {
        return undefined;
      }
      current = (current as Record<string, unknown>)[key];
    }

    return current;
  }
}

/**
 * 创建带有默认模板的模板渲染器
 * 预注册常用模板
 *
 * **默认模板**：
 * - `header`: 文件头部注释（包含时间戳）
 * - `permission-const`: 权限常量声明
 * - `type-export`: TypeScript 类型导出
 *
 * @returns 配置好的模板渲染器
 *
 * @example
 * ```typescript
 * const renderer = createTemplateRenderer();
 * const header = renderer.render('header', { timestamp: new Date() });
 * // 输出:
 * // // Auto-generated by @mtpc/codegen
 * // // Generated at: [时间戳]
 * // // Do not edit manually
 * ```
 */
export function createTemplateRenderer(): TemplateRenderer {
  const renderer = new TemplateRenderer();

  // 头部模板
  renderer.register(
    'header',
    `// Auto-generated by @mtpc/codegen
// Generated at: {{ timestamp }}
// Do not edit manually
`
  );

  // 权限常量模板
  renderer.register('permission-const', `export const {{ name }} = '{{ code }}' as const;`);

  // 类型导出模板
  renderer.register('type-export', `export type {{ name }} = {{ type }};`);

  return renderer;
}
