import type { ResourceDefinition } from '@mtpc/core';
import { compileResourcePermissions } from '@mtpc/core';
import type { GeneratedFile, MetadataOptions } from '../types.js';

/**
 * 资源元数据输出接口（用于 UI 消费）
 *
 * 定义了资源元数据的完整结构，包含：
 * - 基本信息（名称、显示名、描述等）
 * - 特性开关（增删改查列表）
 * - 权限列表
 * - 字段定义
 */
interface ResourceMetadataOutput {
  /** 资源名称 */
  name: string;
  /** 显示名称 */
  displayName: string;
  /** 复数名称 */
  pluralName: string;
  /** 描述 */
  description?: string;
  /** 图标 */
  icon?: string;
  /** 分组 */
  group?: string;
  /** 是否隐藏 */
  hidden: boolean;
  /** 特性开关 */
  features: {
    /** 创建 */
    create: boolean;
    /** 读取 */
    read: boolean;
    /** 更新 */
    update: boolean;
    /** 删除 */
    delete: boolean;
    /** 列表 */
    list: boolean;
  };
  /** 权限列表 */
  permissions: Array<{
    /** 权限代码 */
    code: string;
    /** 操作 */
    action: string;
    /** 描述 */
    description?: string;
  }>;
  /** 字段列表 */
  fields: Array<{
    /** 字段名 */
    name: string;
    /** 字段类型 */
    type: string;
    /** 是否必填 */
    required: boolean;
  }>;
}

/**
 * 生成元数据 JSON 文件
 *
 * 根据资源定义生成 JSON 格式的元数据文件，供前端 UI 使用。
 * 包含资源的完整元信息，可用于动态生成 UI 界面。
 *
 * @param resources - 资源定义数组
 * @param options - 元数据生成选项
 * @returns 生成的 JSON 文件
 *
 * @example
 * ```typescript
 * const result = generateMetadata(
 *   [userResource, postResource],
 *   {
 *     outputFile: 'metadata.json',
 *     includePermissions: true,
 *     includeFeatures: true
 *   }
 * );
 * ```
 */
export function generateMetadata(
  resources: ResourceDefinition[],
  options: MetadataOptions = {}
): GeneratedFile {
  const {
    outputFile = 'metadata.json',
    includePermissions = true,
    includeFeatures = true,
  } = options;

  const metadata: ResourceMetadataOutput[] = resources.map(resource => {
    const permissions = compileResourcePermissions(resource.name, resource.permissions);

    return {
      name: resource.name,
      displayName: resource.metadata.displayName ?? resource.name,
      pluralName: resource.metadata.pluralName ?? resource.name + 's',
      description: resource.metadata.description,
      icon: resource.metadata.icon,
      group: resource.metadata.group,
      hidden: resource.metadata.hidden ?? false,
      features: includeFeatures
        ? {
            create: resource.features.create,
            read: resource.features.read,
            update: resource.features.update,
            delete: resource.features.delete,
            list: resource.features.list,
          }
        : (undefined as any),
      permissions: includePermissions
        ? permissions.map(p => ({
            code: p.code,
            action: p.action,
            description: p.description,
          }))
        : [],
      fields: extractFields(resource.schema),
    };
  });

  return {
    path: outputFile,
    content: JSON.stringify({ resources: metadata }, null, 2),
    type: 'json',
  };
}

/**
 * 生成 TypeScript 元数据文件
 *
 * 生成类型安全的 TypeScript 元数据文件，包含：
 * - ResourceMetadata 接口定义
 * - resourceMetadata 常量对象
 * - 辅助函数（getResourceMetadata、getVisibleResources、getResourcesByGroup）
 *
 * @param resources - 资源定义数组
 * @param options - 元数据生成选项
 * @returns 生成的 TypeScript 文件
 *
 * @example
 * 生成的代码：
 * ```typescript
 * export interface ResourceMetadata { ... }
 * export const resourceMetadata: Record<string, ResourceMetadata> = { ... }
 * export function getResourceMetadata(name: string): ResourceMetadata | undefined { ... }
 * export function getVisibleResources(): ResourceMetadata[] { ... }
 * export function getResourcesByGroup(group: string): ResourceMetadata[] { ... }
 * ```
 */
export function generateMetadataTS(
  resources: ResourceDefinition[],
  options: MetadataOptions = {}
): GeneratedFile {
  const { outputFile = 'metadata.ts' } = options;

  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    '/**',
    ' * Resource metadata type',
    ' * 资源元数据类型',
    ' */',
    'export interface ResourceMetadata {',
    '  name: string;',
    '  displayName: string;',
    '  pluralName: string;',
    '  description?: string;',
    '  icon?: string;',
    '  group?: string;',
    '  hidden: boolean;',
    '  features: {',
    '    create: boolean;',
    '    read: boolean;',
    '    update: boolean;',
    '    delete: boolean;',
    '    list: boolean;',
    '  };',
    '  permissions: Array<{',
    '    code: string;',
    '    action: string;',
    '    description?: string;',
    '  }>;',
    '  fields: Array<{',
    '    name: string;',
    '    type: string;',
    '    required: boolean;',
    '  }>;',
    '}',
    '',
    '/**',
    ' * All resources metadata',
    ' * 所有资源的元数据映射',
    ' */',
    'export const resourceMetadata: Record<string, ResourceMetadata> = {',
  ];

  for (const resource of resources) {
    const permissions = compileResourcePermissions(resource.name, resource.permissions);
    const fields = extractFields(resource.schema);

    lines.push(`  '${resource.name}': {`);
    lines.push(`    name: '${resource.name}',`);
    lines.push(`    displayName: '${resource.metadata.displayName ?? resource.name}',`);
    lines.push(`    pluralName: '${resource.metadata.pluralName ?? resource.name + 's'}',`);

    if (resource.metadata.description) {
      lines.push(`    description: '${resource.metadata.description}',`);
    }
    if (resource.metadata.icon) {
      lines.push(`    icon: '${resource.metadata.icon}',`);
    }
    if (resource.metadata.group) {
      lines.push(`    group: '${resource.metadata.group}',`);
    }

    lines.push(`    hidden: ${resource.metadata.hidden ?? false},`);
    lines.push('    features: {');
    lines.push(`      create: ${resource.features.create},`);
    lines.push(`      read: ${resource.features.read},`);
    lines.push(`      update: ${resource.features.update},`);
    lines.push(`      delete: ${resource.features.delete},`);
    lines.push(`      list: ${resource.features.list},`);
    lines.push('    },');

    lines.push('    permissions: [');
    for (const perm of permissions) {
      lines.push(
        `      { code: '${perm.code}', action: '${perm.action}'${perm.description ? `, description: '${perm.description}'` : ''} },`
      );
    }
    lines.push('    ],');

    lines.push('    fields: [');
    for (const field of fields) {
      lines.push(
        `      { name: '${field.name}', type: '${field.type}', required: ${field.required} },`
      );
    }
    lines.push('    ],');

    lines.push('  },');
  }

  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get resource metadata by name');
  lines.push(' * 根据名称获取资源元数据');
  lines.push(' */');
  lines.push('export function getResourceMetadata(name: string): ResourceMetadata | undefined {');
  lines.push('  return resourceMetadata[name];');
  lines.push('}');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get all visible resources');
  lines.push(' * 获取所有可见资源（未隐藏的资源）');
  lines.push(' */');
  lines.push('export function getVisibleResources(): ResourceMetadata[] {');
  lines.push('  return Object.values(resourceMetadata).filter(r => !r.hidden);');
  lines.push('}');
  lines.push('');
  lines.push('/**');
  lines.push(' * Get resources by group');
  lines.push(' * 根据分组获取资源');
  lines.push(' */');
  lines.push('export function getResourcesByGroup(group: string): ResourceMetadata[] {');
  lines.push('  return Object.values(resourceMetadata).filter(r => r.group === group);');
  lines.push('}');
  lines.push('');

  return {
    path: outputFile,
    content: lines.join('\n'),
    type: 'typescript',
  };
}

/**
 * 从 Zod Schema 中提取字段信息
 *
 * 解析 Zod Schema 定义，提取字段名、类型和是否必填等信息。
 * 支持嵌套对象、数组、枚举等复杂类型。
 *
 * @param schema - Zod Schema 对象
 * @returns 提取的字段信息数组
 */
function extractFields(schema: any): Array<{ name: string; type: string; required: boolean }> {
  const fields: Array<{ name: string; type: string; required: boolean }> = [];

  if (schema._def.typeName !== 'ZodObject') {
    return fields;
  }

  const shape = schema._def.shape();

  for (const [name, value] of Object.entries(shape)) {
    const zodType = value as any;
    fields.push({
      name,
      type: getZodTypeName(zodType),
      required: !isOptional(zodType),
    });
  }

  return fields;
}

/**
 * 获取 Zod 类型的名称
 *
 * 将 Zod 类型转换为简化的字符串类型名称。
 * 支持基本类型、数组、对象、枚举、记录等。
 *
 * @param schema - Zod Schema 对象
 * @returns 类型名称字符串
 *
 * 类型映射：
 * - ZodString → string
 * - ZodNumber → number
 * - ZodBoolean → boolean
 * - ZodDate → date
 * - ZodArray → array<T>
 * - ZodObject → object
 * - ZodEnum → enum
 * - ZodRecord → record
 * - 其他 → unknown
 */
function getZodTypeName(schema: any): string {
  const typeName = schema._def.typeName;

  switch (typeName) {
    case 'ZodString':
      return 'string';
    case 'ZodNumber':
      return 'number';
    case 'ZodBoolean':
      return 'boolean';
    case 'ZodDate':
      return 'date';
    case 'ZodArray':
      return `array<${getZodTypeName(schema._def.type)}>`;
    case 'ZodObject':
      return 'object';
    case 'ZodOptional':
    case 'ZodNullable':
    case 'ZodDefault':
      return getZodTypeName(schema._def.innerType ?? schema._def.type);
    case 'ZodEnum':
      return 'enum';
    case 'ZodRecord':
      return 'record';
    default:
      return 'unknown';
  }
}

/**
 * 检查 Zod 类型是否为可选
 *
 * 判断给定的 Zod Schema 是否被 Optional、Nullable 或 Default 包装。
 *
 * @param schema - Zod Schema 对象
 * @returns 是否为可选类型
 */
function isOptional(schema: any): boolean {
  const typeName = schema._def.typeName;
  return typeName === 'ZodOptional' || typeName === 'ZodNullable' || typeName === 'ZodDefault';
}
