import type { Permission, ResourceDefinition } from '@mtpc/core';
import { compileResourcePermissions } from '@mtpc/core';
import { toPascalCase, toSnakeCase } from '@mtpc/shared';
import type { GeneratedFile, PermissionOptions } from '../types.js';

/**
 * Generate permission code constants
 */
export function generatePermissionCodes(
  resources: ResourceDefinition[],
  options: PermissionOptions = {}
): GeneratedFile {
  const { outputFile = 'permissions.ts', format = 'const', prefix = '' } = options;

  // Collect all permissions
  const allPermissions: Permission[] = [];
  for (const resource of resources) {
    const perms = compileResourcePermissions(resource.name, resource.permissions);
    allPermissions.push(...perms);
  }

  let content: string;

  switch (format) {
    case 'enum':
      content = generateEnumFormat(allPermissions, prefix);
      break;
    case 'object':
      content = generateObjectFormat(resources, prefix);
      break;
    case 'const':
    default:
      content = generateConstFormat(allPermissions, prefix);
      break;
  }

  return {
    path: outputFile,
    content,
    type: 'typescript',
  };
}

/**
 * Generate const format
 */
function generateConstFormat(permissions: Permission[], prefix: string): string {
  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    '/**',
    ' * Permission code constants',
    ' */',
    '',
  ];

  for (const perm of permissions) {
    const constName = `${prefix}${perm.resource.toUpperCase()}_${perm.action.toUpperCase()}`;
    lines.push(`export const ${constName} = '${perm.code}' as const;`);
  }

  lines.push('');
  lines.push('/**');
  lines.push(' * All permission codes');
  lines.push(' */');
  lines.push('export const PERMISSIONS = {');

  for (const perm of permissions) {
    const key = `${perm.resource.toUpperCase()}_${perm.action.toUpperCase()}`;
    lines.push(`  ${key}: '${perm.code}',`);
  }

  lines.push('} as const;');
  lines.push('');
  lines.push('export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate enum format
 */
function generateEnumFormat(permissions: Permission[], prefix: string): string {
  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    '/**',
    ' * Permission codes enum',
    ' */',
    `export enum ${prefix}Permission {`,
  ];

  for (const perm of permissions) {
    const enumKey = `${toPascalCase(perm.resource)}${toPascalCase(perm.action)}`;
    lines.push(`  ${enumKey} = '${perm.code}',`);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate object format (grouped by resource)
 */
function generateObjectFormat(resources: ResourceDefinition[], prefix: string): string {
  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    '/**',
    ' * Permission codes by resource',
    ' */',
    `export const ${prefix}Permissions = {`,
  ];

  for (const resource of resources) {
    lines.push(`  ${resource.name}: {`);

    for (const perm of resource.permissions) {
      const code = `${resource.name}:${perm.action}`;
      lines.push(`    ${perm.action}: '${code}',`);
    }

    lines.push('  },');
  }

  lines.push('} as const;');
  lines.push('');
  lines.push(`export type ${prefix}PermissionCode = `);
  lines.push(
    `  typeof ${prefix}Permissions[keyof typeof ${prefix}Permissions][keyof typeof ${prefix}Permissions[keyof typeof ${prefix}Permissions]];`
  );
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate permission code types
 */
export function generatePermissionTypes(resources: ResourceDefinition[]): GeneratedFile {
  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    '/**',
    ' * Resource names',
    ' */',
    'export type ResourceName =',
  ];

  for (let i = 0; i < resources.length; i++) {
    const suffix = i === resources.length - 1 ? ';' : ' |';
    lines.push(`  | '${resources[i].name}'${suffix}`);
  }

  lines.push('');
  lines.push('/**');
  lines.push(' * Actions by resource');
  lines.push(' */');
  lines.push('export type ResourceActions = {');

  for (const resource of resources) {
    const actions = resource.permissions.map(p => `'${p.action}'`).join(' | ');
    lines.push(`  ${resource.name}: ${actions};`);
  }

  lines.push('};');
  lines.push('');
  lines.push('/**');
  lines.push(' * Permission code type');
  lines.push(' */');
  lines.push('export type PermissionCode<R extends ResourceName = ResourceName> =');
  lines.push('  `${R}:${ResourceActions[R]}`;');
  lines.push('');

  return {
    path: 'permission-types.ts',
    content: lines.join('\n'),
    type: 'typescript',
  };
}
