import type { ResourceDefinition } from '@mtpc/core';
import { toSnakeCase } from '@mtpc/shared';
import type { GeneratedFile, SchemaOptions } from '../types.js';

/**
 * 生成 Drizzle ORM 数据库 Schema 文件
 *
 * 根据资源定义生成 Drizzle ORM 的表结构定义，包括：
 * - 主键和租户字段
 * - 资源字段映射
 * - 时间戳字段（可选）
 * - 审计字段（如果启用）
 * - 软删除字段（如果启用）
 * - 租户索引
 *
 * @param resources - 资源定义数组
 * @param options - Schema 生成选项
 * @returns 生成的 Drizzle Schema 文件
 *
 * @example
 * ```typescript
 * const result = generateDrizzleSchema(
 *   [userResource, postResource],
 *   { outputFile: 'schema.ts', tenantColumn: 'tenant_id', timestamps: true }
 * );
 * ```
 */
export function generateDrizzleSchema(
  resources: ResourceDefinition[],
  options: SchemaOptions = {}
): GeneratedFile {
  const { outputFile = 'schema.ts', tenantColumn = 'tenant_id', timestamps = true } = options;

  const lines: string[] = [
    '// Auto-generated by @mtpc/codegen',
    '// Do not edit manually',
    '',
    'import {',
    '  pgTable,',
    '  uuid,',
    '  text,',
    '  varchar,',
    '  integer,',
    '  boolean,',
    '  timestamp,',
    '  jsonb,',
    '  index,',
    "} from 'drizzle-orm/pg-core';",
    '',
  ];

  for (const resource of resources) {
    const tableName = toSnakeCase(resource.name);
    const varName = resource.name + 'Table';

    lines.push(`/**`);
    lines.push(` * ${resource.metadata.displayName ?? resource.name} table`);
    lines.push(` * ${resource.metadata.displayName ?? resource.name} 数据表`);
    lines.push(` */`);
    lines.push(`export const ${varName} = pgTable('${tableName}', {`);

    // ID column
    lines.push("  id: uuid('id').primaryKey().defaultRandom(),");

    // Tenant column
    lines.push(`  tenantId: uuid('${tenantColumn}').notNull(),`);

    // Resource fields
    const fields = extractSchemaFields(resource.schema);
    for (const field of fields) {
      if (field.name === 'id' || field.name === 'tenantId') continue;

      const columnDef = fieldToColumn(field);
      lines.push(`  ${field.name}: ${columnDef},`);
    }

    // Timestamps
    if (timestamps) {
      lines.push(
        "  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),"
      );
      lines.push(
        "  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),"
      );
    }

    // Audit fields if enabled
    if (resource.features.advanced.audit) {
      lines.push("  createdBy: uuid('created_by'),");
      lines.push("  updatedBy: uuid('updated_by'),");
    }

    // Soft delete if enabled
    if (resource.features.advanced.softDelete) {
      lines.push("  deletedAt: timestamp('deleted_at', { withTimezone: true }),");
      lines.push("  deletedBy: uuid('deleted_by'),");
    }

    lines.push('}, (table) => ({');
    lines.push(`  tenantIdx: index('${tableName}_tenant_idx').on(table.tenantId),`);
    lines.push('}));');
    lines.push('');
  }

  // Export all tables
  lines.push('/**');
  lines.push(' * All tables');
  lines.push(' * 所有表的聚合导出');
  lines.push(' */');
  lines.push('export const tables = {');

  for (const resource of resources) {
    lines.push(`  ${resource.name}: ${resource.name}Table,`);
  }

  lines.push('};');
  lines.push('');

  return {
    path: outputFile,
    content: lines.join('\n'),
    type: 'typescript',
  };
}

/**
 * 从 Zod Schema 中提取字段信息
 *
 * 解析 Zod Schema 定义，提取字段名、类型、是否必填、
 * 最大长度和是否为 UUID 等元数据信息。
 *
 * @param schema - Zod Schema 对象
 * @returns 提取的字段信息数组
 */
function extractSchemaFields(schema: any): Array<{
  name: string;
  type: string;
  required: boolean;
  maxLength?: number;
  isUuid?: boolean;
}> {
  const fields: Array<{
    name: string;
    type: string;
    required: boolean;
    maxLength?: number;
    isUuid?: boolean;
  }> = [];

  if (schema._def.typeName !== 'ZodObject') {
    return fields;
  }

  const shape = schema._def.shape();

  for (const [name, value] of Object.entries(shape)) {
    const zodType = unwrap(value as any);
    const checks = zodType._def.checks ?? [];

    fields.push({
      name,
      type: zodType._def.typeName,
      required: !isOptional(value as any),
      maxLength: checks.find((c: any) => c.kind === 'max')?.value,
      isUuid: checks.some((c: any) => c.kind === 'uuid'),
    });
  }

  return fields;
}

/**
 * 解包 Zod 类型的包装器
 *
 * 移除 ZodOptional、ZodNullable、ZodDefault 等包装器，
 * 返回内部的原始类型。
 *
 * @param schema - Zod Schema 对象
 * @returns 解包后的 Schema
 */
function unwrap(schema: any): any {
  const typeName = schema._def.typeName;

  if (typeName === 'ZodOptional' || typeName === 'ZodNullable' || typeName === 'ZodDefault') {
    return unwrap(schema._def.innerType ?? schema._def.type);
  }

  return schema;
}

/**
 * 检查 Zod 类型是否为可选
 *
 * 判断给定的 Zod Schema 是否被 Optional 或 Nullable 包装。
 *
 * @param schema - Zod Schema 对象
 * @returns 是否为可选类型
 */
function isOptional(schema: any): boolean {
  const typeName = schema._def.typeName;
  return typeName === 'ZodOptional' || typeName === 'ZodNullable';
}

/**
 * 将字段转换为 Drizzle 列定义
 *
 * 根据 Zod 类型和字段属性，生成对应的 Drizzle 列定义字符串。
 *
 * 支持的类型映射：
 * - ZodString (uuid) → uuid()
 * - ZodString (maxLength <= 255) → varchar()
 * - ZodString → text()
 * - ZodNumber → integer()
 * - ZodBoolean → boolean()
 * - ZodDate → timestamp()
 * - ZodArray/ZodObject/ZodRecord → jsonb()
 *
 * @param field - 字段信息
 * @returns Drizzle 列定义字符串
 */
function fieldToColumn(field: {
  name: string;
  type: string;
  required: boolean;
  maxLength?: number;
  isUuid?: boolean;
}): string {
  const columnName = toSnakeCase(field.name);
  let def: string;

  switch (field.type) {
    case 'ZodString':
      if (field.isUuid) {
        def = `uuid('${columnName}')`;
      } else if (field.maxLength && field.maxLength <= 255) {
        def = `varchar('${columnName}', { length: ${field.maxLength} })`;
      } else {
        def = `text('${columnName}')`;
      }
      break;

    case 'ZodNumber':
      def = `integer('${columnName}')`;
      break;

    case 'ZodBoolean':
      def = `boolean('${columnName}')`;
      break;

    case 'ZodDate':
      def = `timestamp('${columnName}', { withTimezone: true })`;
      break;

    case 'ZodArray':
    case 'ZodObject':
    case 'ZodRecord':
      def = `jsonb('${columnName}')`;
      break;

    default:
      def = `text('${columnName}')`;
  }

  if (field.required) {
    def += '.notNull()';
  }

  return def;
}

/**
 * 生成 SQL Schema（用于数据库迁移）
 *
 * 生成纯 SQL 的 CREATE TABLE 语句，可用于数据库迁移脚本。
 *
 * @param resources - 资源定义数组
 * @param options - Schema 生成选项
 * @returns 生成的 SQL 文件
 *
 * @example
 * 生成的 SQL：
 * ```sql
 * CREATE TABLE IF NOT EXISTS users (
 *   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *   tenant_id UUID NOT NULL,
 *   name TEXT NOT NULL,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
 *   updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
 * );
 * CREATE INDEX IF NOT EXISTS users_tenant_idx ON users(tenant_id);
 * ```
 */
export function generateSQLSchema(
  resources: ResourceDefinition[],
  options: SchemaOptions = {}
): GeneratedFile {
  const { outputFile = 'schema.sql', tenantColumn = 'tenant_id', timestamps = true } = options;

  const lines: string[] = ['-- Auto-generated by @mtpc/codegen', '-- Do not edit manually', ''];

  for (const resource of resources) {
    const tableName = toSnakeCase(resource.name);

    lines.push(`-- ${resource.metadata.displayName ?? resource.name}`);
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);
    lines.push('  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
    lines.push(`  ${tenantColumn} UUID NOT NULL,`);

    const fields = extractSchemaFields(resource.schema);
    for (const field of fields) {
      if (field.name === 'id' || field.name === 'tenantId') continue;

      const columnName = toSnakeCase(field.name);
      const sqlType = fieldToSQLType(field);
      const nullable = field.required ? ' NOT NULL' : '';
      lines.push(`  ${columnName} ${sqlType}${nullable},`);
    }

    if (timestamps) {
      lines.push('  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,');
      lines.push('  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,');
    }

    if (resource.features.advanced.softDelete) {
      lines.push('  deleted_at TIMESTAMP WITH TIME ZONE,');
    }

    // Remove trailing comma
    const lastLine = lines[lines.length - 1];
    lines[lines.length - 1] = lastLine.slice(0, -1);

    lines.push(');');
    lines.push('');
    lines.push(
      `CREATE INDEX IF NOT EXISTS ${tableName}_tenant_idx ON ${tableName}(${tenantColumn});`
    );
    lines.push('');
  }

  return {
    path: outputFile,
    content: lines.join('\n'),
    type: 'sql',
  };
}

/**
 * 将字段类型转换为 SQL 类型
 *
 * 根据 Zod 类型和字段属性，生成对应的 PostgreSQL 数据类型。
 *
 * 类型映射：
 * - ZodString (uuid) → UUID
 * - ZodString (maxLength) → VARCHAR(n)
 * - ZodString → TEXT
 * - ZodNumber → INTEGER
 * - ZodBoolean → BOOLEAN
 * - ZodDate → TIMESTAMP WITH TIME ZONE
 * - ZodArray/ZodObject/ZodRecord → JSONB
 *
 * @param field - 字段信息
 * @returns SQL 数据类型字符串
 */
function fieldToSQLType(field: { type: string; maxLength?: number; isUuid?: boolean }): string {
  switch (field.type) {
    case 'ZodString':
      if (field.isUuid) return 'UUID';
      if (field.maxLength) return `VARCHAR(${field.maxLength})`;
      return 'TEXT';
    case 'ZodNumber':
      return 'INTEGER';
    case 'ZodBoolean':
      return 'BOOLEAN';
    case 'ZodDate':
      return 'TIMESTAMP WITH TIME ZONE';
    case 'ZodArray':
    case 'ZodObject':
    case 'ZodRecord':
      return 'JSONB';
    default:
      return 'TEXT';
  }
}
